Converting errors to strings
aws/ota-for-aws-iot-embedded-sdk pull request #100
Opened 2020-12-04 08:18 UTC by divekarshubham

*Issue #, if available:*

*Description of changes:*
Implemented strerr functions in ota, ota_mqtt and ota_http components

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-04 18:51 UTC, yanjos-dev requested changes

2020-12-04 18:51 UTC, yanjos-dev commented on source/ota.c
>                      err ) );
Shouldn't we have a strerror function for OtaOsStatus_t as well?

2020-12-06 02:00 UTC, yanjos-dev approved these changes

2020-12-06 02:08 UTC, cobusve approved these changes

2020-12-06 02:36 UTC, merged