Add cast for size_t
aws/ota-for-aws-iot-embedded-sdk pull request #200
Opened 2021-03-18 17:51 UTC by pvyawaha

*Issue #, if available:* #199

*Description of changes:*
This change adds a cast when logging size_t type .

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-19 05:25 UTC, ser90368141 commented
Hi pvyawaha!
Please add casting in these two places.
https://github.com/aws/ota-for-aws-iot-embedded-sdk/blob/5d7c7f6bdaaef1dddcf0b353d68e01037d7680f6/source/ota.c#L1627-L1630

https://github.com/aws/ota-for-aws-iot-embedded-sdk/blob/5d7c7f6bdaaef1dddcf0b353d68e01037d7680f6/source/ota.c#L2003-L2004
I added these changes and the library built successfully.
Thank!

2021-03-22 18:32 UTC, yanjos-dev submitted a review, later dismissed

2021-03-23 16:49 UTC, divekarshubham approved these changes

2021-03-23 17:00 UTC, divekarshubham approved these changes

2021-03-23 18:00 UTC, gkwicker requested changes
See comments.

2021-03-23 18:00 UTC, gkwicker commented on source/ota.c
> +                        OTA_JobParse_strerror( jobDoc.parseErr ), ( unsigned long ) jobDoc.jobIdLength ) );
See previous comment.

2021-03-23 23:07 UTC, pvyawaha commented on source/ota.c
> +                        ( unsigned long ) valueLength ) );
%zu was not used for portability reason with older VS. https://docs.microsoft.com/en-us/previous-versions/tcxf1dw6(v=vs.140)?redirectedfrom=MSDN

2021-03-23 23:28 UTC, gkwicker approved these changes

2021-03-23 23:28 UTC, merged