Renaming OS timer methods ()
aws/ota-for-aws-iot-embedded-sdk pull request #202
Opened 2021-04-01 06:40 UTC by ser90368141

*Issue:*
[Build error in C ++ projects issue](https://github.com/aws/ota-for-aws-iot-embedded-sdk/issues/201)

*Description of changes:*
Changing the OS name of methods for working with timers for a successful build by the C ++ compiler (rename delete to deleteTimer)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-01 18:04 UTC, divekarshubham requested changes
Please add `starttimer`, `stoptimer`, `deletetimer` to `tools/lexicon.txt`. You would also need to format `ota.c` using Uncrustify and the configuration specifies in `tools/
uncrustify.cfg`

2021-04-01 21:40 UTC, archigup commented
Hi @ser90368141, thanks for the PR!

For formatting, we use Uncrustify 0.66.1.
If you need help with the formatting/spelling checks, or would like me to push the fix for them for you, let me know.

2021-04-05 04:51 UTC, ser90368141 commented
> Hi @ser90368141, thanks for the PR!
> 
> For formatting, we use Uncrustify 0.66.1.
> If you need help with the formatting/spelling checks, or would like me to push the fix for them for you, let me know.

Hi @archigup!
I will be glad if you can help with formatting. I have not used uncrustify before.

2021-04-05 18:33 UTC, divekarshubham approved these changes

2021-04-05 19:15 UTC, gkwicker approved these changes

2021-04-05 19:15 UTC, merged