Add CBMC proof of requestJobMqtt function
aws/ota-for-aws-iot-embedded-sdk pull request #263
Opened 2021-08-18 16:25 UTC by Bujain

Add CBMC proof of requestJobMqtt function

Description
-----------
Add CBMC proof files of requestJobMqtt function

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is formatted using Uncrustify.
- [ ] I have read and applied the rules stated in CONTRIBUTING.md. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-31 23:42 UTC, divekarshubham commented on test/cbmc/proofs/requestJob_Mqtt/Makefile
> +
Please remove unused variables.

2021-09-01 00:00 UTC, divekarshubham requested changes

2021-09-01 00:00 UTC, divekarshubham commented on test/cbmc/proofs/requestJob_Mqtt/requestJob_Mqtt_harness.c
> +    pAgentCtx = &agent;
Why do you have two agent context? Maybe do this:
`pAgentCtx->pOtaInterface = &otaInterface`

2021-09-01 00:06 UTC, divekarshubham commented on test/cbmc/proofs/requestJob_Mqtt/requestJob_Mqtt_harness.c
> +    requestJob_Mqtt( pAgentCtx );
Can we pass `&agent` here directly?

2021-09-01 20:09 UTC, Bujain commented on test/cbmc/proofs/requestJob_Mqtt/requestJob_Mqtt_harness.c
> +    requestJob_Mqtt( pAgentCtx );
Updated in fe1ecdf

2021-09-01 20:09 UTC, Bujain commented on test/cbmc/proofs/requestJob_Mqtt/requestJob_Mqtt_harness.c
> +    otaInterface.mqtt = mqtt;
Updated in fe1ecdf

2021-09-01 20:09 UTC, Bujain commented on test/cbmc/proofs/requestJob_Mqtt/requestJob_Mqtt_harness.c
> +OtaMqttStatus_t publish( const char * const pacTopic,
Updated in fe1ecdf

2021-09-01 20:09 UTC, Bujain commented on test/cbmc/proofs/requestJob_Mqtt/requestJob_Mqtt_harness.c
> +    return status;
Updated in fe1ecdf

2021-09-01 20:09 UTC, Bujain commented on test/cbmc/proofs/requestJob_Mqtt/Makefile
> +
Updated in fe1ecdf

2021-09-02 16:35 UTC, divekarshubham approved these changes

2021-09-09 22:32 UTC, aggarg approved these changes

2021-09-09 23:03 UTC, merged