Add the CBMC proof of requestFileBlock_Mqtt function
aws/ota-for-aws-iot-embedded-sdk pull request #273
Opened 2021-08-23 22:22 UTC by Bujain

Add the CBMC proof of requestFileBlock_Mqtt function

Description
-----------
Added the CBMC proof files for requestFileBlock_Mqtt function

Checklist:
----------

- [x ] I have tested my changes. No regression in existing tests.
- [ x] My code is formatted using Uncrustify.
- [x ] I have read and applied the rules stated in CONTRIBUTING.md. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-01 00:10 UTC, divekarshubham commented on test/cbmc/proofs/requestFileBlock_Mqtt/requestFileBlock_Mqtt_harness.c
> +     * The size of the image is always less than 4GB. */
Could you elaborate on the limit of `INT32_MAX - OTA_FILE_BLOCK_SIZE`

2021-09-01 00:10 UTC, divekarshubham requested changes
Please apply suggestions from https://github.com/aws/ota-for-aws-iot-embedded-sdk/pull/263

2021-09-02 16:39 UTC, divekarshubham approved these changes

2021-09-09 22:32 UTC, aggarg approved these changes

2021-09-09 22:48 UTC, merged