Add CBMC proof of OTA_CBOR_Decode_GetStreamResponseMessage
aws/ota-for-aws-iot-embedded-sdk pull request #278
Opened 2021-08-25 16:53 UTC by Bujain

Add CBMC proof of OTA_CBOR_Decode_GetStreamResponseMessage

Description
-----------
Added CBMC proof files for OTA_CBOR_Decode_GetStreamResponseMessage function

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is formatted using Uncrustify.
- [ ] I have read and applied the rules stated in CONTRIBUTING.md. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-02 17:01 UTC, divekarshubham requested changes

2021-09-02 17:01 UTC, divekarshubham commented on test/cbmc/proofs/OTA_CBOR_Decode_GetStreamResponseMessage/OTA_CBOR_Decode_GetStreamResponseMessage_harness.c
> +}
NIT: Can apply to all functions below:
```suggestion
{
   returnCborError();
}

CborError returnCborError( )
{
    CborError err;
    return err;
}
```

2021-09-02 17:58 UTC, divekarshubham submitted a review, later dismissed

2021-09-07 23:08 UTC, Bujain commented on test/cbmc/proofs/OTA_CBOR_Decode_GetStreamResponseMessage/OTA_CBOR_Decode_GetStreamResponseMessage_harness.c
> +}
Done, thank you.

2021-09-07 23:09 UTC, Bujain commented on test/cbmc/proofs/OTA_CBOR_Decode_GetStreamResponseMessage/OTA_CBOR_Decode_GetStreamResponseMessage_harness.c
> +}
Done, thank you !

2021-09-08 01:42 UTC, paulbartell submitted a review, later dismissed

2021-09-09 23:22 UTC, divekarshubham approved these changes

2021-09-09 23:28 UTC, aggarg approved these changes

2021-09-09 23:30 UTC, merged