Add CBMC proof of OTA_Suspend
aws/ota-for-aws-iot-embedded-sdk pull request #338
Opened 2021-11-01 23:36 UTC by Bujain

Add CBMC proof of OTA_Suspend function. 

Description
-----------
This PR adds files required for the CBMC proof of OTA_Suspend function.

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is formatted using Uncrustify.
- [ ] I have read and applied the rules stated in CONTRIBUTING.md. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-11-03 18:09 UTC, AniruddhaKanhere requested changes

2021-11-03 18:09 UTC, AniruddhaKanhere commented on test/cbmc/proofs/OTA_Suspend/OTA_Suspend_harness.c
> +    __CPROVER_assume( otaAgent.pOtaInterface != NULL );
Why is this assumption needed if you are initializing the pointer with the address of the variable on line 42 above?

2021-11-03 18:09 UTC, AniruddhaKanhere commented on test/cbmc/proofs/OTA_Suspend/OTA_Suspend_harness.c
> +    /* OtaInterfaces in the otaAgent are always checked in OTA_Init to be non-NULL. */
Maybe this comment should be moved above line 42.

2021-11-03 18:43 UTC, AniruddhaKanhere commented on test/cbmc/proofs/OTA_Suspend/OTA_Suspend_harness.c
> +#include "otaAgentStubs.c"
Is there no way around this? I would love the C file not to be `#include`ed.

2021-11-09 22:53 UTC, AniruddhaKanhere commented on test/cbmc/proofs/OTA_Suspend/OTA_Suspend_harness.c
> +OtaOsStatus_t timerStop( OtaTimerId_t otaTimerId )
Can otaTimerId take any value? I was under the impression that it can only be a few values.

2021-11-09 22:53 UTC, AniruddhaKanhere commented on test/cbmc/proofs/OTA_Suspend/OTA_Suspend_harness.c
> +    otaAgent.pOtaInterface = &otaInterface;
Comment on why this cannot be NULL?

2021-11-16 18:48 UTC, AniruddhaKanhere approved these changes

2021-11-16 19:57 UTC, paulbartell approved these changes

2021-11-16 21:16 UTC, merged