Add CBMC proof of initializeLocalBuffer
aws/ota-for-aws-iot-embedded-sdk pull request #363
Opened 2021-11-15 22:55 UTC by Bujain

Add CBMC proof of initializeLocalBuffer function

Description
-----------
This PR adds files required for the CBMC proof of initializeLocalBuffers function.

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is formatted using Uncrustify.
- [ ] I have read and applied the rules stated in CONTRIBUTING.md. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-12-09 23:41 UTC, AniruddhaKanhere requested changes

2021-12-09 23:41 UTC, AniruddhaKanhere commented on test/cbmc/proofs/initializeLocalBuffers/initializeLocalBuffers_harness.c
> +    initializeLocalBuffers();
We should havoc the otaAgent before calling this function.

2021-12-10 18:05 UTC, AniruddhaKanhere approved these changes

2021-12-10 20:23 UTC, paulbartell commented
Couldn't this be covered in a proof of OTA_Init?

2021-12-10 21:01 UTC, Bujain commented
> Couldn't this be covered in a proof of OTA_Init?

Yes, it could've been covered in that. The proof of this function is included just for the sake of completeness.

2021-12-14 22:00 UTC, merged