Add OTA cbor decode/encode files
aws/ota-for-aws-iot-embedded-sdk pull request #46
Opened 2020-10-29 20:44 UTC by tgsong

*Description of changes:*

Review OTA cbor files.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-02 23:01 UTC, divekarshubham submitted a review, later dismissed

2020-11-03 00:02 UTC, gkwicker requested changes
See comments.

2020-11-03 01:21 UTC, gkwicker approved these changes

2020-11-03 18:31 UTC, divekarshubham approved these changes

2020-11-03 18:33 UTC, merged