Update readme for CBMC local runs
aws/ota-for-aws-iot-embedded-sdk pull request #473
Opened 2023-02-16 19:39 UTC by kstribrnAmzn

Description
-----------
* Adds readme section describing CBMC local execution
* Corrects mispelling of 'pieces'
* Adds comment explaining thingname size bounds

Checklist:
----------

- [N/A] I have tested my changes. No regression in existing tests.
- [N/A] My code is formatted using Uncrustify.
- [ x ] I have read and applied the rules stated in CONTRIBUTING.md. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-16 23:47 UTC, feliperodri requested changes

2023-02-16 23:47 UTC, feliperodri commented on README.md
> +  * For example, the **requestJob_Mqtt** proof  fails on my MAC with the following error
```suggestion
  * For example, the **requestJob_Mqtt** proof fails on macOS with the following error:
```

2023-02-16 23:47 UTC, feliperodri commented on README.md
> +To solve this, replace `strncpy` with `__builtin___strncpy_ch on [this line](https://github.com/aws/ota-for-aws-iot-embedded-sdk/blob/main/test/cbmc/proofs/requestJob_Mqtt/Makefile#L16).
```suggestion
To solve this issue, replace `strncpy` with `__builtin___strncpy_ch` on [this line](https://github.com/aws/ota-for-aws-iot-embedded-sdk/blob/main/test/cbmc/proofs/requestJob_Mqtt/Makefile#L16).
```

2023-02-17 17:48 UTC, kstribrnAmzn commented
Thanks for the review and suggestions @feliperodri! I've applied them.

2023-02-17 18:31 UTC, feliperodri approved these changes
LGTM 🚢 it!

2023-02-20 20:03 UTC, merged