Add OTA OS interface and POSIX implementation
aws/ota-for-aws-iot-embedded-sdk pull request #49
Opened 2020-11-02 20:50 UTC by pvyawaha

*Issue #, if available:*

*Description of changes:* This change add the OTA OS interface header as well as header and source for OTA OS POSIX implementation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-05 19:42 UTC, divekarshubham requested changes
Need brief explanations of functions in `ota_os_posix.c` about how the function performs the actions

2020-11-09 19:08 UTC, tgsong requested changes

2020-11-10 18:35 UTC, divekarshubham approved these changes

2020-11-10 19:32 UTC, cobusve approved these changes

2020-11-10 20:06 UTC, tgsong approved these changes

2020-11-10 20:07 UTC, merged