Adding OTA agent files
aws/ota-for-aws-iot-embedded-sdk pull request #52
Opened 2020-11-03 17:29 UTC by divekarshubham

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-09 01:30 UTC, tgsong requested changes

2020-11-09 19:41 UTC, tgsong requested changes

2020-11-15 23:26 UTC, divekarshubham commented on source/ota.c
> +    if( setError != OTA_ERR_NONE )
Removed in https://github.com/aws/ota-for-aws-iot-embedded-sdk/commit/b29e98996f388af68e3a033ad7464cd78f77716a

2020-11-18 17:33 UTC, pvyawaha commented on source/ota.c
> +            if( 1 /*otaAgent.xOTA_EventQueue != NULL*/ )
This is fixed

2020-11-18 17:35 UTC, pvyawaha commented on source/include/ota.h
> +#include <stdio.h>
I think we should use the file ptr for windows/linux

2020-11-18 17:35 UTC, pvyawaha commented on source/include/ota.h
> +        FILE * pFile;         /*!< File type is stdio FILE structure after file is open for write. */
See my comment above

2020-11-18 17:38 UTC, pvyawaha commented on source/include/ota_private.h
> +    void * const pDestOffset;              /*!< Pointer or offset to where we will store the value, if not ~0. */
Updated.

2020-11-18 17:41 UTC, pvyawaha commented on source/ota.c
> +};
Updated.

2020-11-18 17:43 UTC, pvyawaha commented on source/ota.c
> +static OtaFileContext_t * getFreeContext( void )
Removed.

2020-11-18 19:28 UTC, tgsong commented on source/ota.c
> +    pthread_exit( NULL );
it's still here, on both this pr and development branch.

2020-11-18 19:28 UTC, tgsong commented on source/include/ota.h
> +#include <stdio.h>
I remember MISRA prohibits the use of `stdio.h` header. Why we need this to be a concrete type? Only the pal cares about this pointer, and they can convert it right?

2020-11-18 21:52 UTC, tgsong commented on source/ota.c
> +};
Where is this updated? It's not showing here.

2020-11-18 21:54 UTC, pvyawaha commented on source/include/ota.h
> +#include <stdio.h>
yes I can note it and we can do a separate PR as we will have to update the PALs for linux and windows as well.

2020-11-18 22:37 UTC, divekarshubham commented on source/ota.c
> +};
This is moved inside pOtaInterface, can be found in https://github.com/aws/ota-for-aws-iot-embedded-sdk/pull/52/commits/6db0fb222600b968b2c8cb037c61577c4aab2a2c

2020-11-19 00:07 UTC, divekarshubham commented on source/ota.c
> +    pthread_exit( NULL );
Removed in https://github.com/aws/ota-for-aws-iot-embedded-sdk/commit/5f3ea308664d2f0c0de1a7798a9551f2fba6e4f4

2020-11-19 00:09 UTC, divekarshubham commented on source/ota.c
> +        *ppvParamAdd = true;
updated in https://github.com/aws/ota-for-aws-iot-embedded-sdk/commit/5f3ea308664d2f0c0de1a7798a9551f2fba6e4f4

2020-11-19 00:16 UTC, divekarshubham commented on source/ota.c
> +            err = parseJobDocFromCustomCallback( pJson, messageLength, pFileContext );
fixed in https://github.com/aws/ota-for-aws-iot-embedded-sdk/commit/5f3ea308664d2f0c0de1a7798a9551f2fba6e4f4

2020-11-19 02:16 UTC, pvyawaha approved these changes, later dismissed

2020-11-19 02:23 UTC, tgsong submitted a review, later dismissed

2020-11-19 04:26 UTC, tgsong approved these changes, later dismissed

2020-11-19 04:28 UTC, tgsong approved these changes

2020-11-19 23:16 UTC, n9wxu approved these changes

2020-11-19 23:20 UTC, merged