Add header and source of OTA MQTT component
aws/ota-for-aws-iot-embedded-sdk pull request #53
Opened 2020-11-03 17:39 UTC by pvyawaha

*Issue #, if available:*

*Description of changes:* The change adds the internal OTA MQTT components , the header and implementation. This component handles the control and well as data over MQTT for Over-the-Air updates.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-05 02:23 UTC, divekarshubham submitted a review, later dismissed
Here are some common comments:
1. Should check that msgBuffer is not null in all functions
2. Should change the implementation and the use of snprintf
3. Remove dynamic memory allocations

2020-11-08 22:54 UTC, tgsong requested changes

2020-11-11 22:29 UTC, tgsong requested changes

2020-11-11 22:33 UTC, tgsong requested changes

2020-11-12 04:59 UTC, tgsong requested changes

2020-11-13 17:44 UTC, n9wxu approved these changes

2020-11-13 18:47 UTC, n9wxu approved these changes, later dismissed

2020-11-13 18:53 UTC, tgsong approved these changes, later dismissed

2020-11-13 18:54 UTC, tgsong approved these changes, later dismissed

2020-11-13 18:59 UTC, yanjos-dev approved these changes, later dismissed

2020-11-13 19:04 UTC, yanjos-dev approved these changes

2020-11-13 19:04 UTC, tgsong approved these changes

2020-11-13 19:05 UTC, merged