Updating files for LTS release
aws/ota-for-aws-iot-embedded-sdk pull request #81
Opened 2020-11-21 23:10 UTC by divekarshubham

*Issue #, if available:*

*Description of changes:*
1. Updated OTA Library Version Number (2.0.0)
2. Added new file Security.md
3. Added new file manifest.yml 
4. Added new file CHANGELOG.md
5. Moved lexicon.cfg file under tools folder
6. Changed cmock folder name to unity in tools

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-22 01:17 UTC, tgsong commented
@divekarshubham why cmock is renamed to unity?

2020-11-23 19:18 UTC, tgsong requested changes
We shouldn't rename cmock folder to unity since we're still using.

2020-11-23 21:22 UTC, tgsong approved these changes

2020-11-23 23:51 UTC, pvyawaha approved these changes

2020-11-24 00:31 UTC, gkwicker approved these changes

2020-11-24 00:33 UTC, merged